apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-github
  labels:
    app: EKS
spec:
  selector:
    matchLabels:
        app: EKS
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: EKS
    spec:
      containers:
        - name: chalapan
          image: 097084951758.dkr.ecr.us-east-1.amazonaws.com/chalapan
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
